### ISSUE TITLE
Flacky tests "goToReportsNative" sometimes doesn't redirect to reports

### ISSUE THREAD

**Issue by dianabarsan** [medic/angular10-migration#140] opened 2021-02-15 07:05 UTC
```
1) Submit Delivery Report open delivery form
  - Failed: waitElementToBeVisible timed out looking for By(css selector, *[id="reports-list"])
  Wait timed out after 15006ms
```

Example build: https://github.com/medic/cht-core/runs/1901242176#step:18:605

**Comment by dianabarsan** [comment] 2021-02-16 07:05
I haven't been able to replicate this (or see an obvious reason why it would happen).
The build where I saw it fail was rerun (successfully), so the artifact was lost.

**Comment by dianabarsan** [comment] 2021-02-16 07:35
Ok, I found a new build that failed similartly: https://github.com/medic/cht-core/runs/1903188242

Different test but it called the same function, that would redirect to reports. 
This run should have an artifact available to download, and it looks like the redirect to reports didn't work: 
![image](https://user-images.githubusercontent.com/35681649/108031917-4a2fe900-703a-11eb-84d4-84fe231a5c85.png)

```
1) Family form Submit Add Family form
  - Failed: waitElementToBeVisible timed out looking for By(css selector, *[id="reports-list"])
  Wait timed out after 15006ms
```

I've updated the title of the issue to reflect this.

**Comment by dianabarsan** [comment] 2021-02-16 11:12
My suspicion is that some test doesn't await for something that ends up performing a redirect farther down the execution chain, while this other test is running.

**Comment by latin-panda** [comment] 2021-02-17 07:05
I was able to get the error, I'm going to try fixing it 😬

**Comment by latin-panda** [comment] 2021-02-18 07:03
I couldn't reproduce the redirection behaviour but end up fixing a couple of other things. I haven't seen the flaky test back again but moving this ticket back to ToDo in case we get the error again 🤞

**Comment by dianabarsan** [comment] 2021-02-18 07:08
Cool, thanks @latin-panda . 
I've added a new label, so it's clear that reproducing is an issue.

**Comment by dianabarsan** [comment] 2021-02-20 16:12
This just happened again in this build: https://github.com/medic/cht-core/runs/1942374212

![image](https://user-images.githubusercontent.com/35681649/108601793-20165800-73a7-11eb-9bd5-71f4353d3182.png)

**Comment by dianabarsan** [comment] 2021-02-20 16:40
And again here: https://github.com/medic/cht-core/pull/6952/checks?check_run_id=1942499228

**Comment by dianabarsan** [comment] 2021-02-22 15:55
Yet another manifestation of the same issue: 
![image](https://user-images.githubusercontent.com/35681649/108733407-28050200-7537-11eb-92de-353cb1398eb0.png)

build: https://github.com/medic/cht-core/runs/1940713713

**Closed as completed** 2021-09-28 10:54 UTC
